### ISSUE TITLE
Use crowdsec blocklist mirror

### ISSUE THREAD

**Issue by williamdes** [0x767676/crowdsec-mikrotik#2]
I implemented your script in a cleaner and easier way directly in the blocklist mirror: https://github.com/crowdsecurity/cs-blocklist-mirror/pull/20

**Comment by 0x767676** [comment]
Awesome work @williamdes !

**Comment by williamdes** [comment]
Let me know if you want to document this here
I will probably mention your project when I write a blog post for it
